basePath: /
definitions:
  handler.Userr:
    type: object
info:
  contact: {}
  description: LOXXX search
  title: Manka Api
  version: "1.0"
paths:
  /channel/create:
    post:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Userr'
      summary: Show an account
      tags:
      - accounts
swagger: "2.0"
