// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package tutorial

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Channel struct {
	ID        int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Name      string
}

type Message struct {
	ID           int32
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	Content      string
	AuthorID     int32
	PodchannelID int32
}

type Podchannel struct {
	ID        int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Name      string
	Type      string
	ChannelID int32
}

type User struct {
	ID        int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Name      string
	Email     string
}
